//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated from a template.
//
//     Manual changes to this file may cause unexpected behavior in your application.
//     Manual changes to this file will be overwritten if the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace GuessTheAnimal
{
    using System;
    using System.Collections.Generic;
    using System.ComponentModel.DataAnnotations;

    public partial class AnimalDetail
    {
        public string SelectedYes { get; set; }
        public string SelectedNo { get; set; }

        [Required(ErrorMessage ="Please answer the question")]
        public string SelectedAnswer { get; set; }

    }
}
